/**
 * GN-file coverage, sourced from the data repo's v1/coverage.json
 * (generated by scripts/build_index.py — the truth, not a guess).
 * Default (before load, or if unreachable): assume full coverage,
 * which matches the 2026-09-24 scan (332/332 DS divisions ship GN files).
 */

import { COVERAGE_URL } from "../services/dataHosts";

let missingDs = new Set<string>(); // "province|district|ds"
let missingDist = new Set<string>(); // "province|district"
let loaded = false;

export async function loadCoverage(): Promise<void> {
  if (loaded) return;
  loaded = true;
  try {
    const r = await fetch(COVERAGE_URL);
    if (!r.ok) return;
    const c = await r.json();
    const miss: string[] = Array.isArray(c?.gn_missing_ds) ? c.gn_missing_ds : [];
    missingDist = new Set(
      miss.filter((m) => m.split("|").length === 2).map((m) => m)
    );
    missingDs = new Set(miss.filter((m) => m.split("|").length === 3));
  } catch {
    /* keep defaults — full coverage assumed */
  }
}

export type GnCoverage = "ok" | "missing";

/** Whether GN files exist upstream for a given DS division. */
export function gnFolderStatus(
  provinceName: string | undefined,
  districtName: string | undefined,
  dsName: string
): GnCoverage {
  if (!provinceName || !districtName) return "ok";
  if (missingDist.has(`${provinceName}|${districtName}`)) return "missing";
  if (missingDs.has(`${provinceName}|${districtName}|${dsName}`)) return "missing";
  return "ok";
}
